name: Code quality

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm i
      - name: Run check
        run: |
          pnpm check

permissions:
  contents: write
concurrency:
  group: build-and-test
  cancel-in-progress: true
