name: Lint and Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: build-and-test
  cancel-in-progress: true
jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          bun install
      - name: Run Format
        run: |
          bun format
      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "Apply formatting"
  # check:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 3
  #   steps:
  #     - uses: actions/checkout@v3.5.2
  #     - uses: oven-sh/setup-bun@v1
  #       with:
  #         bun-version: latest
  #     - name: Install dependencies
  #       run: |
  #         bun install
  #     - name: Run check
  #       run: |
  #         bun check
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          bun install
      - name: Run Linter
        run: |
          bun lint
