name: Lint and Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: build-and-test
  cancel-in-progress: true
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node JS 18
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm i
      - name: Run Prettier
        run: |
          pnpm format
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "Apply formatting"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node JS 18
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm i
      - name: Run eslint
        run: |
          pnpm lint --fix
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "Apply linting"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: pnpm/action-setup@v2
      with:
        version: 8
      - name: Setup Node JS 18
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm i
      - name: Run tests
        run: |
          pnpm test
